version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: shortenedUrl-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  app:
    build: .
    restart: always
    working_dir: /home/node/app
    command: npm run prod
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/shortenedUrl-app
      - MODE=Local
    ports:
      - "3001:3001"
    volumes:
      - ./package.json:/home/node/app/package.json
      - ./src:/home/node/app/src
    links:
      - postgres
